# Generated by Django 5.1.2 on 2024-10-16 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yapen_id', models.CharField(blank=True, max_length=50, null=True)),
                ('yapen_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('yogei_id', models.CharField(blank=True, max_length=50, null=True)),
                ('yogei_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('naver_id', models.CharField(blank=True, max_length=50, null=True)),
                ('naver_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('bnb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bnb_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
