# Generated by Django 5.1.2 on 2024-10-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforminfomodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
