# Generated by Django 5.1.2 on 2024-10-20 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_platforminfomodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRoomInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('yapen_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('yogei_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('naver_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bnb_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
