# Generated by Django 5.1.2 on 2024-10-20 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_platformroominfomodel_default_room_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformroominfomodel',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='platformroominfomodel',
            constraint=models.UniqueConstraint(fields=('user', 'display_order'), name='unique_order_on_user'),
        ),
    ]
