# Generated by Django 5.1.2 on 2024-10-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_platformroominfomodel_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='platformroominfomodel',
            name='unique_order_on_user',
        ),
    ]
