# Generated by Django 5.1.2 on 2024-10-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_platformroominfomodel_unique_order_on_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformroominfomodel',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
