# Generated by Django 5.1.2 on 2024-10-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_platformroominfomodel_display_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformRoomInfoModel',
        ),
    ]
