# Generated by Django 5.1.2 on 2024-10-20 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_platformroominfomodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRoomInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('default_room_name', models.CharField(max_length=50, unique=True)),
                ('yapen_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('yogei_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('naver_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bnb_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'display_order'), name='unique_display_order')],
            },
        ),
    ]
