# Generated by Django 5.1.2 on 2024-10-30 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_platforminfomodel_platformauthinfomodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardRoomInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('standard_room_name', models.CharField(max_length=50, unique=True)),
                ('room_quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yapen_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('yogei_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('naver_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bnb_room_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('standard_room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.standardroominfomodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='standardroominfomodel',
            constraint=models.UniqueConstraint(fields=('user', 'display_order'), name='unq_display_order'),
        ),
    ]
