# Generated by Django 5.1.2 on 2024-10-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_standardroominfomodel_roominfomodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roominfomodel',
            old_name='standard_room_name',
            new_name='standard_room_info',
        ),
    ]
