# Generated by Django 5.1.2 on 2024-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_standard_room_name_roominfomodel_standard_room_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'app_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformsAuthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'platforms_auth_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformsRoomsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'platforms_rooms_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StandardRoomsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'standard_rooms_info',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='platformroominfomodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roominfomodel',
            name='standard_room_info',
        ),
        migrations.RemoveField(
            model_name='roominfomodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='standardroominfomodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlatformAuthInfoModel',
        ),
        migrations.DeleteModel(
            name='PlatformRoomInfoModel',
        ),
        migrations.DeleteModel(
            name='RoomInfoModel',
        ),
        migrations.DeleteModel(
            name='StandardRoomInfoModel',
        ),
    ]
