name: CI/CD Pipeline

on:
  push:
    branches:
      - main # main 브랜치로 푸시될 때 실행

jobs:
  # build done by dockerfile

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:$(date +%Y%m%d) -f ./frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$(date +%Y%m%d)

      - name: Build & Push Spring Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-be-rah:$(date +%Y%m%d) -f ./backend_spring/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-be-rah:$(date +%Y%m%d)

      - name: Build & Push Django Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-be-rah:$(date +%Y%m%d) -f ./backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-be-rah:$(date +%Y%m%d)

      - name: copy docker-compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./docker-compose.yml
          target: /home/${{ secrets.SERVER_USER }}/rah/docker-compose.yml
        # run: |
        #   echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        #   scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/rah/docker-compose.yml

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/next-fe-rah:$(date +%Y%m%d)
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-be-rah:$(date +%Y%m%d)
            docker pull ${{ secrets.DOCKER_USERNAME }}/django-be-rah:$(date +%Y%m%d)
            docker-compose down
            docker-compose up -d
