name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치로 푸시될 때 실행

jobs:
  # build done by dockerfile

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f ./frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          
      - name: Build & Push Spring Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-be-rah:latest -f ./backend_spring/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-be-rah:latest
          
      - name: Build & Push Django Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-be-rah:latest -f ./backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-be-rah:latest


  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/next-fe-rah:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-be-rah:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/django-be-rah:latest
            docker-compose down
            docker-compose up -d

